# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: Congcong Cai's homepage!
description: 摸鱼使我快乐 touching fish makes me happy! C++ and WASM developer

## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: Asia/Shanghai # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## => Author and Social
##############################
author:
  type: # "person" (default), "organization"
  name: Congcong Cai
  avatar: favicon.ico # path or url of avatar image (square)
  email: congongcai0907@163.com
  zhihu: cai-cong-cong-55 # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  linkedin: ACoAACnUpi0BZtbpRnapsPWl4mEcFphHT5TC1DY # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github: HerrCai0907 # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm: congcongcai # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: HerrCai0907/HerrCai0907.github.io
repository_tree: main

## => Paths
##############################
paths:
  root: # title link url, "/" (default)
  home: # home layout url, "/" (default)
  archive: # "/archive.html" (default)
  rss: # "/feed.xml" (default)

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id: # LeanCloud App id
    app_key: # LeanCloud App key
    app_class: # LeanCloud App class

## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
